config/routes.rb
# frozen_string_literal: true

id_name_constraint = { id: %r{[^/]+?}, format: /json|html/ }.freeze
Rails.application.routes.draw do

  require 'sidekiq/web'
  require 'sidekiq_unique_jobs/web'

  mount Sidekiq::Web => '/sidekiq', constraints: AdminRouteConstraint.new

  namespace :admin do
    resources :users, :only => [:edit, :update, :edit_blacklist, :update_blacklist, :alt_list] do
      member do
        get :edit_blacklist
        post :update_blacklist
        get :request_password_reset
        post :password_reset
      end
      collection do
        get :alt_list
      end
    end
    resource :dashboard, :only => [:show]
    resources :exceptions, only: [:index, :show]
    resource :reowner, controller: 'reowner', only: [:new, :create]
    resource :stuck_dnp, controller: "stuck_dnp", only: %i[new create]
    resources :staff_notes, only: [:index]
    resources :danger_zone, only: [:index] do
      collection do
        put :uploading_limits
      end
    end
  end
  resources :edit_histories
  namespace :moderator do
    resource :dashboard, :only => [:show]
    resources :ip_addrs, :only => [:index] do
      collection do
        get :export
      end
    end
    namespace :post do
      resource :approval, :only => [:create, :destroy]
      resources :disapprovals, :only => [:create, :index]
      resources :posts, :only => [:delete, :undelete, :expunge, :confirm_delete] do
        member do
          get :confirm_delete
          post :expunge
          post :delete
          post :undelete
          get :confirm_move_favorites
          post :move_favorites
          get :confirm_ban
          post :ban
          post :unban
          post :regenerate_thumbnails
          post :regenerate_videos
        end
      end
    end
  end
  resources :popular, only: [:index]
  namespace :maintenance do
    namespace :user do
      resource :count_fixes, only: [:new, :create]
      resource :email_notification, :only => [:show, :destroy]
      resource :password_reset, :only => [:new, :create, :edit, :update]
      resource :login_reminder, :only => [:new, :create]
      resource :deletion, :only => [:show, :destroy]
      resource :email_change, :only => [:new, :create]
      resource :dmail_filter, :only => [:edit, :update]
      resource :api_key, only: %i[show update destroy] do
        post :view
      end
    end
  end

  resources :tickets, except: %i[destroy] do
    member do
      post :claim
      post :unclaim
    end
  end

  resources :takedowns do
    collection do
      post :count_matching_posts
    end
    member do
      post :add_by_ids
      post :add_by_tags
      post :remove_by_ids
    end
  end

  resources :artists, constraints: id_name_constraint do
    member do
      put :revert
    end
    collection do
      get :show_or_new
    end
  end
  resources :artist_urls, only: [:index]
  resources :artist_versions, :only => [:index] do
    collection do
      get :search
    end
  end
  resources :bans
  resources :bulk_update_requests do
    member do
      post :approve
    end
  end
  resources :comments do
    resource :votes, :controller => "comment_votes", :only => [:create, :destroy]
    collection do
      get :search
    end
    member do
      post :hide
      post :unhide
      post :warning
    end
  end
  resources :comment_votes, only: [:index, :delete, :lock] do
    collection do
      post :lock
      post :delete
    end
  end
  resources :dmails, :only => [:new, :create, :index, :show, :destroy] do
    member do
      put :mark_as_read
      put :mark_as_unread
    end
    collection do
      put :mark_all_as_read
    end
  end
  resource :dtext_preview, :only => [:create]
  resources :favorites, :only => [:index, :create, :destroy]
  resources :forum_posts do
    resource :votes, controller: "forum_post_votes"
    member do
      post :hide
      post :unhide
      post :warning
    end
    collection do
      get :search
    end
  end
  resources :forum_topics do
    member do
      post :hide
      post :unhide
      post :subscribe
      post :unsubscribe
    end
    collection do
      post :mark_all_as_read
    end
    resource :visit, :controller => "forum_topic_visits"
  end
  resources :forum_categories
  resources :help_pages, controller: "help", path: "help"
  resources :ip_bans
  resources :upload_whitelists, except: %i[show] do
    collection do
      get :is_allowed
    end
  end
  resources :email_blacklists, only: [:new, :create, :destroy, :index]
  resource :iqdb_queries, :only => [:show] do
    collection do
      post :show
    end
  end
  resources :mod_actions
  resources :news_updates
  resources :notes do
    collection do
      get :search
    end
    member do
      put :revert
    end
  end
  resources :note_versions, :only => [:index]
  resources :pools do
    member do
      put :revert
    end
    collection do
      get :gallery
    end
    resource :order, :only => [:edit], :controller => "pool_orders"
  end
  resource :pool_element, :only => [:create, :destroy]
  resources :pool_versions, :only => [:index] do
    member do
      get :diff
    end
  end
  resources :post_replacements, :only => [:index, :new, :create, :destroy] do
    member do
      put :approve
      put :reject
      post :promote
      put :toggle_penalize
    end
  end
  resources :deleted_posts, only: [:index]
  resources :posts, :only => [:index, :show, :update] do
    resources :replacements, :only => [:index, :new, :create], :controller => "post_replacements"
    resource :votes, :controller => "post_votes", :only => [:create, :destroy]
    resource :flag, controller: 'post_flags', only: [:destroy]
    resources :favorites, :controller => "post_favorites", :only => [:index]
    collection do
      get :random
    end
    member do
      get :update_iqdb
      put :revert
      put :copy_notes
      get :show_seq
      put :mark_as_translated
      get :comments, to: "comments#for_post"
    end
    get :similar, :to => "iqdb_queries#index"
  end
  resources :post_votes, only: [:index, :delete, :lock] do
    collection do
      post :lock
      post :delete
    end
  end
  resources :post_events, only: :index
  resources :post_flags, except: [:destroy]
  resources :post_approvals, only: [:index]
  resources :post_versions, :only => [:index] do
    member do
      put :undo
    end
  end
  resource :related_tag, :only => [:show, :update]
  match "related_tag/bulk", to: "related_tags#bulk", via: [:get, :post]
  resource :session, only: [:new, :create, :destroy]
  resources :stats, only: [:index]
  resources :tags, constraints: id_name_constraint do
    resource :correction, :only => [:new, :create, :show], :controller => "tag_corrections"
    collection do
      post :preview
    end
  end
  resources :tag_type_versions
  resources :tag_aliases do
    member do
      post :approve
    end
  end
  resource :tag_alias_request, :only => [:new, :create]
  resources :tag_implications do
    member do
      post :approve
    end
  end
  resource :tag_implication_request, :only => [:new, :create]
  resources :uploads
  resources :users do
    resource :password, :only => [:edit], :controller => "maintenance/user/passwords"
    resource :api_key, :only => [:show, :view, :update, :destroy], :controller => "maintenance/user/api_keys" do
      post :view
    end
    resources :staff_notes, only: [:index, :new, :create], controller: "admin/staff_notes"

    collection do
      get :home
      get :search
      get :upload_limit
      get :custom_style
    end
  end
  resources :user_feedbacks do
    collection do
      get :search
    end
  end
  resources :user_name_change_requests
  resource :user_revert, :only => [:new, :create]
  resources :wiki_pages, constraints: id_name_constraint do
    member do
      put :revert
    end
    collection do
      get :search
      get :show_or_new
    end
  end
  resources :wiki_page_versions, :only => [:index, :show, :diff] do
    collection do
      get :diff
    end
  end
  resources :blips do
    member do
      post :hide
      post :unhide
      post :warning
    end
  end
  resources :post_report_reasons
  resources :post_sets do
    collection do
      get :for_select
    end
    member do
      get :maintainers
      get :post_list
      post :update_posts
      post :add_posts
      post :remove_posts
    end
  end
  resources :post_set_maintainers do
    member do
      get :approve
      get :block
      get :deny
    end
  end
  resource :email do
    collection do
      get :activate_user
      get :resend_confirmation
    end
  end
  resources :mascots, only: [:index, :new, :create, :edit, :update, :destroy]

  options "*all", to: "application#enable_cors"

  # aliases
  resources :wpages, :controller => "wiki_pages"
  resources :ftopics, :controller => "forum_topics"
  resources :fposts, :controller => "forum_posts"

  # legacy aliases
  get "/artist" => redirect {|params, req| "/artists?page=#{req.params[:page]}&search[name]=#{CGI::escape(req.params[:name].to_s)}"}
  get "/artist/index" => redirect {|params, req| "/artists?page=#{req.params[:page]}"}
  get "/artist/show/:id" => redirect("/artists/%{id}")
  get "/artist/show" => redirect {|params, req| "/artists?name=#{CGI::escape(req.params[:name].to_s)}"}
  get "/artist/history/:id" => redirect("/artist_versions?search[artist_id]=%{id}")
  get "/artist/recent_changes" => redirect("/artist_versions")

  get "/comment" => redirect {|params, req| "/comments?page=#{req.params[:page]}"}
  get "/comment/index" => redirect {|params, req| "/comments?page=#{req.params[:page]}"}
  get "/comment/show/:id" => redirect("/comments/%{id}")
  get "/comment/new" => redirect("/comments")
  get("/comment/search" => redirect do |params, req|
    if req.params[:query] =~ /^user:(.+)/i
      "/comments?group_by=comment&search[creator_name]=#{CGI::escape($1)}"
    else
      "/comments/search"
    end
  end)

app/controllers/wiki_pages_controller.rb
# frozen_string_literal: true

class WikiPagesController < ApplicationController
  respond_to :html, :json, :js
  before_action :member_only, :except => [:index, :search, :show, :show_or_new]
  before_action :admin_only, :only => [:destroy]
  before_action :normalize_search_params, :only => [:index]

  def new
    @wiki_page = WikiPage.new(wiki_page_params(:create))
    respond_with(@wiki_page)
  end

  def edit
    if params[:id] =~ /\A\d+\z/
      @wiki_page = WikiPage.find(params[:id])
    else
      @wiki_page = WikiPage.titled(params[:id])
      if @wiki_page.nil? && request.format.symbol == :html
        redirect_to show_or_new_wiki_pages_path(:title => params[:id])
        return
      end
    end
    ensure_can_edit(@wiki_page, CurrentUser.user)
    respond_with(@wiki_page)
  end

  def index
    @wiki_pages = WikiPage.search(search_params).paginate(params[:page], :limit => params[:limit], :search_count => params[:search])
    respond_with(@wiki_pages) do |format|
      format.html do
        if params[:page].nil? || params[:page].to_i == 1
          if @wiki_pages.length == 1
            redirect_to(wiki_page_path(@wiki_pages.first))
          elsif @wiki_pages.length == 0 && params[:search][:title].present? && params[:search][:title] !~ /\*/
            redirect_to(wiki_pages_path(:search => {:title => "*#{params[:search][:title]}*"}))
          end
        end
      end
      format.json do
        render json: @wiki_pages.to_json
        expires_in params[:expiry].to_i.days if params[:expiry]
      end
    end
  end

  def search
  end

  def show
    if params[:id] =~ /\A\d+\z/
      @wiki_page = WikiPage.find(params[:id])
    else
      @wiki_page = WikiPage.titled(params[:id])
    end

    if @wiki_page.present?
      respond_with(@wiki_page)
    elsif request.format.html?
      redirect_to show_or_new_wiki_pages_path(title: params[:id])
    else
      raise ActiveRecord::RecordNotFound
    end
  end

  def create
    @wiki_page = WikiPage.create(wiki_page_params(:create))
    respond_with(@wiki_page)
  end

  def update
    @wiki_page = WikiPage.find(params[:id])
    ensure_can_edit(@wiki_page, CurrentUser.user)
    @wiki_page.update(wiki_page_params(:update))
    respond_with(@wiki_page)
  end

  def destroy
    @wiki_page = WikiPage.find(params[:id])
    @wiki_page.destroy
    if @wiki_page.errors.none?
      flash[:notice] = "Page destroyed"
    else
      flash[:notice] = @wiki_page.errors.full_messages.join("; ")
    end
    respond_with(@wiki_page)
  end

  def revert
    @wiki_page = WikiPage.find(params[:id])
    ensure_can_edit(@wiki_page, CurrentUser.user)
    @version = @wiki_page.versions.find(params[:version_id])
    @wiki_page.revert_to!(@version)
    flash[:notice] = "Page was reverted"
    respond_with(@wiki_page)
  end

  def show_or_new
    @wiki_page = WikiPage.titled(params[:title])
    if @wiki_page
      redirect_to wiki_page_path(@wiki_page)
    else
      @wiki_page = WikiPage.new(:title => params[:title])
      respond_with(@wiki_page)
    end
  end

  private

  def ensure_can_edit(page, user)
    return if user.is_janitor?
    raise User::PrivilegeError.new("Wiki page is locked.") if page.is_locked
  end

  def normalize_search_params
    if params[:title]
      params[:search] ||= {}
      params[:search][:title] = params.delete(:title)
    end
  end

  def wiki_page_params(context)
    permitted_params = %i[body skip_secondary_validations edit_reason]
    permitted_params += %i[is_locked is_deleted] if CurrentUser.is_janitor?
    permitted_params += %i[title] if context == :create || CurrentUser.is_janitor?

    params.fetch(:wiki_page, {}).permit(permitted_params)
  end
end

app/helpers/wiki_pages_helper.rb
# frozen_string_literal: true

module WikiPagesHelper
  def link_to_wiki_or_new(text, tag = text)
    link_to(text, show_or_new_wiki_pages_path(title: tag))
  end

  def multiple_link_to_wiki_or_new(tags)
    safe_join(tags.map { |tag| link_to_wiki_or_new(tag) }, ", ")
  end

  def wiki_page_alias_and_implication_list(wiki_page)
    render "tags/alias_and_implication_list", tag: wiki_page.tag || Tag.new(name: wiki_page.title)
  end

  def wiki_page_post_previews(wiki_page)
    tag.div(id: "wiki-page-posts") do
      if Post.fast_count(wiki_page.title) > 0
        view_all_link = link_to("view all", posts_path(tags: wiki_page.title))
        header = tag.h2("Posts (#{view_all_link})".html_safe)
        header + wiki_page.post_set.presenter.post_previews_html(self)
      end
    end
  end
end

app/views/wiki_pages/_form.html.erb
<div id="form-content">
  <%= error_messages_for("wiki_page") %>

  <%= custom_form_for(@wiki_page) do |f| %>
    <% if @wiki_page.new_record? %>
      <%= f.input :title, error: false, autocomplete: "tag" %>
    <% elsif CurrentUser.is_janitor? %>
      <%= f.input :title, error: false, autocomplete: "tag", hint: "Change to rename this wiki page. Move the tag and update any wikis linking to this page first." %>
    <% else %>
      <h1 id="wiki-page-title"><%= @wiki_page.pretty_title %></h1>
    <% end %>

    <%= f.input :body, as: :dtext, limit: Danbooru.config.wiki_page_max_size %>

    <% if CurrentUser.is_janitor? && @wiki_page.is_deleted? %>
      <%= f.input :is_deleted, :label => "Deleted", :hint => "Uncheck to restore this wiki page" %>
    <% end %>

    <% if CurrentUser.is_janitor? %>
      <%= f.input :is_locked, :label => "Locked" %>
    <% end %>

    <%= f.input :edit_reason, label: "Edit Reason" %>

    <% if @wiki_page.errors[:title].present?  %>
      <%= f.input :skip_secondary_validations, as: :boolean, label: "Force rename", hint: "Ignore the renaming requirements" %>
    <% end %>

    <%= f.button :submit, "Submit" %>
  <% end %>
</div>

app/views/wiki_pages/_quick_search.html.erb
<%= form_tag(wiki_pages_path, :method => :get) do %>
  <%= text_field "search", "title", id: "quick_search_title", placeholder: "Search wiki pages", data: { autocomplete: "wiki-page" } %>
<% end %>

app/views/wiki_pages/_recent_changes.html.erb
<section>
  <h1>Recent Changes (<%= link_to "all", wiki_pages_path(:order => "time") %>)</h1>
  <ul>
    <% WikiPage.recent.each do |page| %>
      <li class="category-<%= page.category_id %>"><%= link_to page.pretty_title, wiki_page_path(page) %></li>
    <% end %>
  </ul>
</section>

app/views/wiki_pages/_search.html.erb
<%= form_search(path: wiki_pages_path) do |f| %>
  <%= f.input :title, label: "Title", hint: "Use * for wildcard searches", autocomplete: "wiki-page" %>
  <%= f.input :body_matches, label: "Body" %>
  <%= f.user :creator %>
  <%= f.input :other_names_match, label: "Other names", hint: "Use * for wildcard searches" %>
  <%= f.input :other_names_present, collection: %w[Yes No], include_blank: true %>
  <%= f.input :hide_deleted, collection: %w[Yes No] %>
  <%= f.input :order, collection: [%w[Name title], %w[Date time], %w[Posts post_count]] %>
<% end %>

app/views/wiki_pages/_secondary_links.html.erb
<% content_for(:secondary_links) do %>
  <li><%= render "wiki_pages/quick_search" %></li>

  <%= subnav_link_to "Listing", wiki_pages_path %>

  <%= subnav_link_to "Search", search_wiki_pages_path %>

  <% if CurrentUser.is_member? %>
    <%= subnav_link_to "New", new_wiki_page_path %>
  <% end %>

  <%= subnav_link_to "Help", help_page_path(id: "wiki") %>

  <% if @wiki_page %>
    <li>|</li>

    <% if @wiki_page.tag.present? %>
      <%= subnav_link_to "Posts (#{@wiki_page.tag.post_count})", posts_path(tags: @wiki_page.title) %>

      <% if CurrentUser.is_member? %>
        <%= subnav_link_to "Edit Tag Type", edit_tag_path(@wiki_page.tag) %>
        <% if CurrentUser.is_janitor? %>
          <%= subnav_link_to "Fix Tag Count", new_tag_correction_path(tag_id: @wiki_page.tag.id) %>
        <% end %>
      <% end %>
    <% end %>

    <% if @wiki_page.persisted? %>
      <%= subnav_link_to "History", wiki_page_versions_path(search: { wiki_page_id: @wiki_page.id }) %>

      <% if CurrentUser.is_member? && params[:action] != "edit" %>
        <%= subnav_link_to "Edit", edit_wiki_page_path(@wiki_page), data: { shortcut: "e" } %>
      <% end %>

      <% if CurrentUser.is_admin? && !@wiki_page.is_deleted? %>
        <%= subnav_link_to "Delete", wiki_page_path(@wiki_page), method: :delete, data: { confirm: "Are you sure you want to delete this wiki page?" } %>
      <% end %>

      <% if CurrentUser.is_member? %>
        <%= subnav_link_to "Report", new_ticket_path(disp_id: @wiki_page.id, qtype: "wiki") %>
      <% end %>
    <% end %>
  <% elsif @wiki_page_version %>
    <li>|</li>

    <%= subnav_link_to "Newest", wiki_page_path(@wiki_page_version.wiki_page_id) %>

    <% if @wiki_page_version.previous %>
      <%= subnav_link_to "Diff", diff_wiki_page_versions_path(otherpage: @wiki_page_version.id, thispage: @wiki_page_version.previous.id) %>
    <% end %>

    <% if CurrentUser.is_member? %>
      <%= subnav_link_to "Revert to", revert_wiki_page_path(@wiki_page_version.wiki_page_id, version_id: @wiki_page_version.id), method: :put, data: { confirm: "Are you sure you want to revert to this version?" } %>
    <% end %>
  <% elsif @thispage %>
    <li>|</li>

    <%= subnav_link_to "Newest", wiki_page_path(@thispage.wiki_page_id) %>

    <%= subnav_link_to "History", wiki_page_versions_path(search: { wiki_page_id: @thispage.wiki_page_id }) %>
  <% end %>
<% end %>

app/views/wiki_pages/_sidebar.html.erb
<aside id="sidebar">
  <%= render "posts/partials/index/blacklist" %>
  <%= render "wiki_pages/recent_changes" %>
</aside>

app/views/wiki_pages/edit.html.erb
<div id="c-wiki-pages">
  <div id="a-edit">
    <%= render "sidebar" %>

    <section id="content">
      <h1>Edit Wiki</h1>

      <% if @wiki_page.visible? %>
        <%= render "form" %>
      <% else %>
        <p>The artist requested removal of this page.</p>
      <% end %>

      <%= wiki_page_alias_and_implication_list(@wiki_page)%>
      <%= wiki_page_post_previews(@wiki_page) %>
      <div class="clearfix"></div>
    </section>
  </div>
</div>

<%= render "secondary_links" %>

<% content_for(:page_title) do %>
  Edit Wiki Page - <%= @wiki_page.title %>
<% end %>

app/views/wiki_pages/index.html.erb
<div id="c-wiki-pages">
  <div id="a-index">
    <%= render "sidebar" %>

    <section id="content">
      <h1>Wiki</h1>

      <%= render "search" %>
      <table class="striped">
        <thead>
          <tr>
            <th>Title</th>
            <th>Last edited</th>
            <th>History</th>
          </tr>
        </thead>
        <tbody>
          <% @wiki_pages.each do |wiki_page| %>
            <tr>
              <td class="category-<%= wiki_page.category_id %>"><%= link_to wiki_page.pretty_title, wiki_page_path(wiki_page) %></td>
              <td><%= compact_time wiki_page.updated_at %> by <%= link_to_user wiki_page.updater %></td>
              <td><%= link_to "History", wiki_page_versions_path(search: { wiki_page_id: wiki_page.id }) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <%= numbered_paginator(@wiki_pages) %>
    </section>
  </div>
</div>

<% content_for(:page_title) do %>
  Wiki
<% end %>

<%= render "secondary_links" %>

app/views/wiki_pages/new.html.erb
<div id="c-wiki-pages">
  <div id="a-new">
    <%= render "sidebar" %>

    <section id="content">
      <h1>New Wiki Page</h1>

      <%= render "form" %>

      <%= wiki_page_alias_and_implication_list(@wiki_page)%>
      <%= wiki_page_post_previews(@wiki_page) %>
      <div class="clearfix"></div>

    </section>
  </div>
</div>

<%= render "secondary_links" %>

<% content_for(:page_title) do %>
  New Wiki Page
<% end %>

app/views/wiki_pages/search.html.erb
<div id="c-wiki-pages">
  <div id="a-search">
    <h1>Search Wiki</h1>

    <%= render "search" %>
  </div>
</div>

<%= render "secondary_links" %>

<% content_for(:page_title) do %>
  Search Wiki
<% end %>

app/views/wiki_pages/show.html.erb
<div id="c-wiki-pages">
  <div id="a-show">
    <%= render "sidebar" %>

    <section id="content">
      <h1 id="wiki-page-title">

        <%= link_to @wiki_page.pretty_title_with_category, posts_path(:tags => @wiki_page.title), :class => "tag-type-#{@wiki_page.category_id}" %>

        <% if @wiki_page.is_locked? %>
          (locked)
        <% end %>

        <% if @wiki_page.is_deleted? %>
          (deleted)
        <% end %>
      </h1>

      <div id="wiki-page-body" class="dtext-container">
        <% if @wiki_page.visible? %>
          <%= format_text(@wiki_page.body, allow_color: true, max_thumbs: 75) %>

          <% if @wiki_page.artist %>
            <p><%= link_to "View artist", @wiki_page.artist %></p>
          <% end %>

          <%= wiki_page_alias_and_implication_list(@wiki_page) %>
        <% else %>
          <p>This artist has requested removal of their information.</p>
        <% end %>
      </div>

        <%= wiki_page_post_previews(@wiki_page) %>
    </section>
  </div>
</div>

<% content_for(:page_title) do %>
  Wiki - <%= @wiki_page.pretty_title %>
<% end %>

<%= render "secondary_links" %>

app/views/wiki_pages/show_or_new.html.erb
<div id="c-wiki-pages">
  <div id="a-show">
    <%= render "sidebar" %>

    <section id="content">
      <h1 id="wiki-page-title">
        <%= link_to @wiki_page.pretty_title_with_category, posts_path(:tags => @wiki_page.title), :class => "tag-type-#{@wiki_page.category_id}" %>
      </h1>
      <div id="wiki-page-body" class="dtext-container">
        <p>This wiki page does not exist. <%= link_to "Create new wiki page", new_wiki_page_path(:wiki_page => {:title => params[:title]}) %>.</p>
      </div>

      <% if @wiki_page.tag&.category == Tag.categories.artist %>
        <%= link_to("View artist",  show_or_new_artists_path(name: @wiki_page.title)) %>
      <% end %>

      <%= wiki_page_alias_and_implication_list(@wiki_page)%>

      <%= wiki_page_post_previews(@wiki_page) %>
    </section>
  </div>
</div>

<%= render "secondary_links" %>

<% content_for(:page_title) do %>
  Wiki - <%= @wiki_page.title %>
<% end %>